version: '3.8'
services:
##'backend-configuration-service'
  configurationservice:
    image: emobilitycontianer.azurecr.io/backend-configuration-service_#{envName}#:#{configTag}#
    container_name: configuration
    restart: always
    ports:
      - '1001:80'
    env_file:
      - ./config.env
    networks:
      - emobility-net
    volumes:
      - config_vol:/tmp

##'csms-algorithmapi-service'
  csmsalgorithmapi:
    image: emobilitycontianer.azurecr.io/csms-algorithmapi-service_#{envName}#:#{apiTag}#
    container_name: algorithmapi
    restart: always
    ports:
      - '1003:80'
    env_file:
      - ./api.env
    depends_on:
      - configurationservice
    networks:
      - emobility-net

##'backend-dataprocessor-service'
  dataprocessor:
    image: emobilitycontianer.azurecr.io/backend-dataprocessor-service_#{envName}#:#{dataTag}#
    container_name: dataprocessor
    restart: always
    ports:
      - '1002:80'
    env_file:
      - ./data.env
    depends_on:
      - configurationservice
    networks:
      - emobility-net

##'backend-housekeepinganddiagnostics-service'
  housekeeping:
    image: emobilitycontianer.azurecr.io/backend-housekeepinganddiagnostics-service_#{envName}#:#{houseKeepingTag}#
    container_name: housekeeping
    restart: always
    ports:
      - '1004:80'
    env_file:
      - ./housekeeping.env
    depends_on:
      - configurationservice
    networks:
      - emobility-net

##'backend-reporting-service'
  reporting:
    image: emobilitycontianer.azurecr.io/backend-reporting-service_#{envName}#:#{reportingTag}#
    container_name: reporting
    restart: always
    ports:
      - '1005:80'
    env_file:
      - ./reporting.env
    depends_on:
      - configurationservice
    networks:
      - emobility-net

##'backend-identity-service'
  identity:
    image: emobilitycontianer.azurecr.io/backend-identity-service_#{envName}#:#{identityTag}#
    container_name: identity
    restart: always
    ports:
      - '1006:80'
    env_file:
      - ./identity.env
    depends_on:
      - configurationservice
    networks:
      - emobility-net

##'csms-algorithm-service'
  csms-algorithm:
    image: emobilitycontianer.azurecr.io/csms-algorithm-service_#{envName}#:#{csmsTag}#
    container_name: csmsalgorithm
    restart: always
    ports:
      - '5056:5056'
    env_file:
      - ./csms.env
    depends_on:
      - csmsalgorithmapi
    networks:
      - emobility-net

##'csms-ocppserver-service'
  ocpp:
    image: emobilitycontianer.azurecr.io/csms-ocppserver-service_#{envName}#:#{ocppTag}#
    container_name: ocppserver
    restart: always
    ports:
      - '3092:3092'
    env_file:
      - ./ocpp.env
    depends_on:
      - csms-algorithm
    networks:
      - emobility-net

##'hmi-on-prem-local-app'
  on-prem:
    image: emobilitycontianer.azurecr.io/on-prem_#{envName}#:#{onpremTag}#
    container_name: on-prem
    restart: always
    ports:
      - '9101:80'
    env_file:
      - ./onprem-sso.env   
    depends_on:
      - configurationservice
    networks:
      - emobility-net

##'hmi-ng-dispenser-app'
  hmi_ng:
    image: emobilitycontianer.azurecr.io/ng-hmi_#{envName}#:#{ngTag}#
    container_name: dispenser
    restart: always
    ports:
      - '9102:80'
    env_file:
      - ./nghmi-sso.env    
    depends_on:
      - on-prem
    networks:
      - emobility-net
## PECC_LOGGER
  pecc_logs:
    image: emobilitycontianer.azurecr.io/data-logger-service_pecc_logs_#{envName}#:#{peccTag}#
    container_name: pecc_logger
    restart: always
    env_file:
      - ./logger.env
    networks:
      - emobility-net

## SECC_LOGGER
  secc_log:
    image: emobilitycontianer.azurecr.io/data-logger-service_secc_logs_#{envName}#:#{seccTag}#
    container_name: secc_logger
    restart: always
    env_file:
      - ./logger.env
    networks:
      - emobility-net

volumes:
  config_vol:

networks:
  emobility-net:
    external: true
